// ORDER CONSTANTS
export const CREATED = "CREATED";
export const COOKED = "COOKED";
export const DRIVER_RECEIVED = "DRIVER_RECEIVED";
export const CANCELLED = "CANCELLED";
export const DELIVERED = "DELIVERED";
export const ACTIVE_EVENTS = [CREATED, COOKED, DRIVER_RECEIVED];
export const INACTIVE_EVENTS = [CANCELLED, DELIVERED];
export const ALL_EVENTS = [...ACTIVE_EVENTS, ...INACTIVE_EVENTS];
